### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [moon201595/C202309#2]
### 없는 파일
- practice/week6/studentGrade.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week8/todo_manager.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week6/studentGrade
    - Error: expected ')' [line 87]
    - Error: expected statement [line 90]
        - 괄호를 맞춰주세요.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 5]
        - main 함수의 반환형과 반환값을 추가해주세요.
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]
        - main 함수의 반환형과 반환값을 추가해주세요.

**Comment by moon201595** [comment]
말씀하신 것들을 다 고쳤는데 week6의 파일 위치확인과 프로젝트 pdf은 파일 명이 잘못된 것 같아서 고쳐넣었습니다. 그리고 week6의 괄호 맞춰 넣었습니다. 그런데 week5의 두 프로그램은 무엇이 잘못된 지 모르겠습니다.. void main으로 되어있는데 int라는 건 무엇인지 모르겠습니다.. 그리구 commit message를 뭐라 할지 몰라서 그냥 issue라고 적었는데 혹시 하나하나 맞춰야하는 것이면 다시 커밋하겠습니다.
