### ISSUE TITLE
week5 워닝의 문제 

### ISSUE THREAD

**Issue by MisooKim2** [moon201595/C202309#3]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 5]
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]

안녕하세요. 위 워닝은 main 함수에 반환형이 void로 설정되어 생기는 문제입니다. 
(아래 코드 참고)

https://github.com/moon201595/C202309/blob/23e4ba6a83e98754ab89443becae57f78c228b99/challenge/week5/functionMulti.c#L5

C 컴파일러의 규칙 상, main 함수는 int 반환형을 가지고, 그에 해당하는 반환값을 보내줘야 합니다.
즉 위 코드에서 반환형을 int 로 변경하고, main 함수 가 닫히기 전에 return 0; 을 추가해서 반환 값을 명시해주시면 됩니다.
예를 들면 아래와 같습니다.
```

int main(){
    // 소스코드
    return 0;
}
```

추가로 커밋 메세지는 Fix #이슈 번호를 넣어주시면 됩니다.
예를 들면 Fix #3 과 같이 표기하시면 됩니다. 
이전 커밋들을 다 새로하실 필요는 없고, 앞으로 커밋 하실때 참고해주세요.

**Comment by moon201595** [comment]
Fix #3
감사합니다 교수님! 모두 커밋 완료 했습니다!
